---
title: "Exercise #3"
subtitle: "Fortgeschrittene Statistische Software für NF"
author: "Anna Tschersich(Martrikelnummer), Name (Martrikelnummer), ..."
date: "`r Sys.Date()`"
output: distill::distill_article
---


## Exercise 1: Initializing git 

### Exercise 1d:

**Strengths:**

a) Git is very fast, efficient and powerful.

b) Git is very helpful working together on a project by tracking all
changes in a project, aiding in teamwork and ensuring transparency.

**Weaknesses:**

a) For beginners, the functionality of git can be very challenging .

b) In very large teams, coordination becomes crucial to prevent loss of
work and conflicts when using Git. 



## Exercise 2: Putting your Repository on GitHub



## Exercise 3: Baby-Names in Munich 

### Exercise 3b:
```{r}
babynames_2022 <- read.csv("/Users/anna/2024-exeRcise-sheet-3/open_data_portal_2022.csv")
babynames_2023 <- read.csv("/Users/anna/2024-exeRcise-sheet-3/vornamen-muenchen-2023.csv")

typeof(babynames_2022$Anzahl) # Antwort: character
typeof(babynames_2023$Anzahl) # Antwort: character 

babynames_2022$Anzahl <- as.numeric(babynames_2022$Anzahl)
babynames_2023$Anzahl <- as.numeric(babynames_2023$Anzahl)

# R doesnt interpret the varibale "Anzahl" as numeric, as there are some values that are not just numbers but also text (e.g.: "4 oder weniger" as a value). 

# My solution is to change the types of the variable "Anzahl" in both datasets from character to numeric. Now the variable has the numerical datatype. Unfortunately all values that had text in it are now "NA" so the counts of some babynames got loss by changing the datatype. 
```


b)  Load the data for both years into R. Check the type of the count
    variable ("Anzahl") and look into the data to determine why it is
    not numeric? Fix the problem in an appropriate manner, it is OK if
    some of the counts are inaccurate because of this. Explain your
    solution and the repercussions.

c)  Calculate the total number of babies born in Munich in 2022
    and 2023. Which year had the bigger baby-boom?

d)  Add a new column `year` to both datasets which holds the correct
    year for each.

e)  Combine both datasets into one using `bind_rows()`.

f)  Combine the counts for same names to determine the most popular
    names across both years. Print out the top 10 names in a nicely
    formatted table for both years. Include a table caption.

## Exercise 4: Open Analysis (4 points)

This exercise is a bit more open-ended. You can choose any dataset from
[Our World in Data](https://ourworldindata.org/) and analyze it, while
determining the research question yourself.

a)  Go to <https://github.com/owid/owid-datasets/tree/master/datasets>
    and choose a dataset that interests you. You can have a look at
    <https://ourworldindata.org/> to gather some inspiration.
b)  Download the dataset and track it in git.
c)  Put the name / title of the dataset and a link to it below.

-   Dataset Name: ...
-   Link: <https://github.com/owid/owid-datasets/>...

d)  Come up with a (research) question you want to answer with the data
    and briefly explain why you believe this is an interesting question
    within one sentence. It should be a question that can be answered
    with the dataset and using R.
e)  Use R to answer your chosen question.
f)  Create a meaningful plot / figure with the dataset. Make sure to
    provide a figure caption (via the chunk options / Rmarkdown) and
    correctly label the figure.

## Final Note

Make sure to push all your commits and changes to GitHub before
submittining the exercise sheet.
